
version: 2

models:
  - name: wines
    description: "This table contains details about wines."
    columns:
      - name: product_id
        description: "Unique identifier for the wine."
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the wine."
        tests:
          - not_null
      - name: release_date
        description: "Date the film was released."
        tests:
          - not_null
      - name: price
        description: "Price to buy a wine."
        tests:
          - not_null
      - name: user_rating
        description: "Rating that users gave the wine."
        tests:
          - not_null
      

  - name: grapes
    description: "This table contains details about grapes."
    columns:
      - name: grape_id
        description: "Unique identifier for the grape."
        tests:
          - unique
          - not_null
      - name: name
        description: "Name of the grape."
        tests:


  - name: wine_grapes
    description: "This table maps wines to the grapes."
    columns:
      - name: product_id
        description: "Identifier for the wine."
        tests:
          - not_null
      - name: grape_id
        description: "Identifier for the grape."
        tests:
          - not_null
  
  
  - name: wine_ratings
    description: "This model aggregates wine data and calculates the average rating for each wine."
    columns:
      - name: product_id
        description: "The unique identifier for each wine."
        tests:
          - unique
          - not_null

      - name: title
        description: "The title of the wine."
        tests:
          - not_null

      - name: release_date
        description: "The release date of the wine."
        tests:
          - not_null

      - name: price
        description: "The price of the wine."
        tests:
          - not_null

      - name: user_rating
        description: "The average user rating for the wine."
        tests:
          - not_null

      - name: grape_count
        description: "The number of grape in the wine."
        tests:
          - not_null