version: 2

sources:
  - name: destination_db
    description: "Raw data from the destination PostgreSQL database."
    database: destination_db
    schema: public
    tables:
      - name: wines
        description: "List of wines."
      - name: grapes
        description: "List of grapes."
      - name: wine_grapes
        description: "Mapping between wines and grapes."